### ISSUE TITLE
Gulp issues

### ISSUE THREAD

**Issue by simonh1000** [AndersSchmidtHansen/Kaidan#5]
Hi,
tried to follow your instructions.
Got an error about rimraf being depreacted but it does not seem to be used so I took that out of package.json.
However after installing dependencies when I ran gulp I ended up with this. I see you had set package.json to download latest versions of everything and fear that may be the source of the problem, as I have not changed anything yet.
Any ideas?

```
[19:16:59] Using gulpfile ~/code/Dropbox/HTML/ghost/content/themes/Mat/gulpfile.js
[19:16:59] Starting 'browser-sync'...
[19:16:59] 'browser-sync' errored after 25 ms
[19:16:59] TypeError: Cannot call method 'map' of null
  at Object.opts.callbacks.files (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/lib/cli/cli-options.js:273:40)
  at /Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/lib/cli/cli-options.js:292:54
  at /Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1139:46
  at /Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1872:16
  at ValueNode.iterate (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2239:12)
  at BitmapIndexedNode.iterate.HashArrayMapNode.iterate [as iterate] (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2232:24)
  at HashArrayMapNode.BitmapIndexedNode.iterate.HashArrayMapNode.iterate [as iterate] (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:2232:24)
  at Map.__iterate (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1870:32)
  at KeyedIterable.mappedSequence.__iterateUncached (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1138:23)
  at seqIterate (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:601:16)
  at KeyedIterable.Seq.__iterate (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:261:14)
  at KeyedIterable.mixin.forEach (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:4265:19)
  at /Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1740:16
  at Map.withMutations (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1848:7)
  at new Map (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1737:20)
  at reify (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1673:37)
  at Map.mixin.map (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:4285:14)
  at /Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/lib/cli/cli-options.js:290:18
  at Map.withMutations (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/node_modules/immutable/dist/immutable.js:1848:7)
  at opts.merge (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/lib/cli/cli-options.js:289:10)
  at /Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/lib/public/init.js:25:33
  at Function.initSingleton [as init] (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/browser-sync/index.js:196:20)
  at Gulp.gulp.task.gulp.src.pipe.run.changed.extension (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/src/config/gulpfile.coffee:26:15)
```

**Comment by AndersSchmidtHansen** [comment]
Hi Simon! Thanks for letting me know, I've not been able to work on Kaidan for quite some time due to studies and work, so I'm not up to date with it. I'll look into it asap, and give you an update on it when i get it working. Would that be ok?  Its very much likely that things are set to grabbing the latest stuff, which can break some dependencies. :) it also looks like browser-sync is bugging up, there has been some big changes to it lately, so maybe rolling it back to an earlier version could fix it.

**Comment by simonh1000** [comment]
Cool, I went back to browser-sync@1.5.0 and got it working, but now i have an exception on the sass side

```
[21:42:23] 'sass' errored after 101 ms
[21:42:23] TypeError: Arguments to path.join must be strings
  at path.js:360:15
  at Array.filter (native)
  at Object.exports.join (path.js:358:36)
  at Object.module.exports (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/gulp-ruby-sass/index.js:65:15)
  at Gulp.gulp.task.gulp.src.pipe.pipe.run.include.extensions (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/src/config/gulpfile.coffee:43:13)
  at module.exports (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
  at Gulp.<anonymous> (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/gulp/index.js:36:18)
  at Gaze.<anonymous> (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:18:14)
  at Gaze.emit (events.js:98:17)
  at Gaze.emit (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:129:32)
  at /Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:415:16
  at StatWatcher._pollers.(anonymous function) (/Users/simon/code/Dropbox/HTML/ghost/content/themes/Mat/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:326:7)
  at StatWatcher.emit (events.js:98:17)
  at StatWatcher._handle.onchange (fs.js:1115:10)
```

**Comment by simonh1000** [comment]
Cool. I've been trying to get the latest ruby-sass working but it is a big
change from before. If I make progress I'll submit a pr

**Comment by DiegoAz** [comment]
Hi @simonh1000 , maybe this can resolve your problem: https://github.com/BrowserSync/browser-sync/issues/440

**Comment by AndersSchmidtHansen** [comment]
Hey @DiegoAz ! Thanks for the tip :) i think simon fixed this with a PR ive just been busy and forgot to close the issue, sorry. I'll close it up now, if something new comes up, let me know !
